regions:
  900:
    regionid: 900
    regioncode: "headscale"
    regionname: "Headscale Embedded"
    nodes:
      - name: "headscale-embedded"
        regionid: 900
        hostname: "192.168.110.16"
        stunport: 3478
        derpport: 8080
        ipv4: "192.168.110.16"
        insecure_for_tests: true
